### ISSUE TITLE
Doesn't scroll

### ISSUE THREAD

**Issue by ghost** [simoncorompt/smooth-scroll#1]
Yo! Your examples doesn't seem to be working. I need to scroll for about 10 sec and then it scrolls for 10px. Could you check it?

**Comment by simoncorompt** [comment]
Hey Andrew!
Sorry, that lib hasn't been updated in a while so it currently has some crossbrowser issues. The delta registered on scroll is pretty inconsistent depending on which device and / or browser you are using. Just checked on my computer and it works just fine.

I currently have no time to take a look at this myself and have no plans on updating it in the near future as it is a pretty old experiment, but if you wanna have a look and find a way to fix it, then create a pull request and I'd be happy to introduce your work in!

For a nice smooth scroll package I'd recommend you to have a try with this lib : https://www.npmjs.com/package/virtual-scroll

Cheers,

Simon

**Comment by ghost** [comment]
I'm not very familiar with JQuery and corresponding **mousewheel** plugin, but probably the problem was with that line:
`var offset = e.deltaY * 0.4;`
I've revealed that deltaY property contains value that equals to 1 or -1, but you assume it to has 100 or -100. I might be wrong. Check 'fixed' version [here](https://codepen.io/AndrewNoskov/pen/NvEavd?editors=0010).

**Comment by simoncorompt** [comment]
Hey, thanks for taking a look at this :)

If you look at the docs, it's stated that the delta can indeed be superior to 1 and -1 :

> This plugin normalizes those values so you get a whole number starting at +-1 and going up in increments of +-1 according to the force or acceleration that is used.
https://github.com/jquery/jquery-mousewheel

So on my trackpad, there might be much more acceleration than on yours maybe? 

Your version works on my end but the scroll is really fast (one small scroll and I get to the bottom easily), also be careful using the original event as it might not work on every browser especially old ones. Do you use a mouse or a trackpad?

Have good day!
